# Generated by Django 2.1.5 on 2019-01-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_query', models.CharField(max_length=100)),
                ('question_answer', models.CharField(max_length=100)),
            ],
        ),
    ]
