# Generated by Django 2.1.5 on 2019-01-12 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var1', models.IntegerField(max_length=3)),
                ('var2', models.IntegerField(max_length=3)),
                ('answer', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='equation',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add.Question'),
        ),
    ]
