# Generated by Django 2.1.5 on 2019-01-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0002_auto_20190112_0737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equation',
            old_name='answer',
            new_name='votes',
        ),
        migrations.RemoveField(
            model_name='equation',
            name='var1',
        ),
        migrations.RemoveField(
            model_name='equation',
            name='var2',
        ),
        migrations.AlterField(
            model_name='equation',
            name='choice_text',
            field=models.CharField(max_length=200),
        ),
    ]
